name: 'Install dependencies'
description: 'Install dependencies'
runs:
  using: 'composite'
  steps:
    - name: Remove .npmrc
      run: rm .npmrc
      shell: bash

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
        scope: '@innomotics'

    - uses: actions/cache@v3
      id: cache
      with:
        key: npm-${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
        path: |
          node_modules
          packages/**/node_modules

    - name: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
