name: Deploy Docs

on:
  workflow_dispatch:

concurrency:
  group: publish-${{ github.sha }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        artifact-name: docs-build 
        
        
